# application.yml

logging-module:
  version: 0.0.5

spring:
  web:
    resources:
      static-locations[0]: "file:home/ec2-user/Board/src/main/resources/static/"
      static-locations[1]: "classpath:/static/"
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: 'true'
      force: 'true'
  datasource:
    password: KDkd4813*
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kddnswlr
    url: jdbc:mysql://3.35.255.89:3306/longstonedb?serverTimezone=UTC&characterEncoding=UTF-8

server: ''
string: ''
//DB: ''
hibernate: ''
error: ''
enabled: 'false'
port: ${PORT:8080}
jpa: ''
whitelabel: ''
properties: ''
show_sql: 'true'

